import os
import json
from concurrent.futures import ThreadPoolExecutor, as_completed
import numpy as np
import pandas as pd
from google import genai
from google.genai import types
from pydantic import BaseModel, Field

import config

class JudgeEvaluation(BaseModel):
    judge_score: float = Field(description="Score between 0.0 and 1.0 representing the correctness, validity, and helpfulness of the agent's response to the user's question.")
    reasoning: str = Field(description="Reasoning explaining the evaluation of the response relative to the user's question, and why this score was assigned.")


def evaluate_response(client: genai.Client, question: str, agent_response: str) -> dict:
    """Uses Gemini to evaluate a question-answer pair and returns a dict with score and reasoning."""
    if client is None:
        # Mock mode: return pseudo-random scores and a mock explanation
        # Add a short delay to simulate real latency for testing concurrency
        import time
        time.sleep(0.1)
        rng = np.random.default_rng(hash(question + agent_response) & 0xffffffff)
        mock_score = round(rng.uniform(0.1, 0.95), 2)
        mock_reasoning = f"Mock evaluation: The response seems reasonably accurate but has some minor issues (Mock score: {mock_score})."
        return {
            "judge_score": mock_score,
            "reasoning": mock_reasoning
        }

    prompt = f"""
    You are an expert AI quality assurance judge evaluating responses generated by a virtual agent assistant.
    
    Evaluate the following user question and virtual agent assistant's response:
    
    User Question:
    "{question}"
    
    Agent's Response:
    "{agent_response}"
    
    Your task:
    1. Check if the agent's response is valid, correct, accurate, and completely answers the user's question.
    2. Assign a judge_score between 0.0 (completely incorrect/incoherent/unhelpful) and 1.0 (completely correct/helpful/accurate).
    3. Provide a clear reasoning explaining your evaluation, highlighting any missing information or discrepancies.
    """

    try:
        response = client.models.generate_content(
            model=config.JUDGE_MODEL,
            contents=prompt,
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                response_schema=JudgeEvaluation,
            ),
        )
        
        parsed_result = response.parsed
        if parsed_result:
            return {
                "judge_score": float(parsed_result.judge_score),
                "reasoning": parsed_result.reasoning
            }
        else:
            # Fallback in case of raw text
            data = json.loads(response.text)
            return {
                "judge_score": float(data.get("judge_score", 0.0)),
                "reasoning": data.get("reasoning", "Parsed result was empty.")
            }
    except Exception as e:
        print(f"Evaluation failed: {e}. Returning default values.")
        return {
            "judge_score": 0.0,
            "reasoning": f"Evaluation error: {e}"
        }


def run_analysis_pipeline(client: genai.Client, similarity_matrix: np.ndarray, input_queries: list[str], low_score_df: pd.DataFrame) -> None:
    """
    For each master_question, find the single best matched question from the dataset (maximum similarity).
    Extract the question, agent_response, overall_score.
    Call Gemini concurrently to score the QA pair.
    Saves the output to config.EVALUATION_CSV.
    """
    print(f"\n--- Running Response Evaluation Agent (Judge Agent) in Parallel ({config.MAX_WORKERS} workers) ---")
    
    num_queries = len(input_queries)
    if num_queries == 0 or low_score_df.empty:
        print("No queries or dataset records available for analysis.")
        return

    # List to store tasks
    tasks = []
    for query_idx, query in enumerate(input_queries):
        similarities = similarity_matrix[query_idx]
        
        # Find index of the highest similarity match (rank = 1)
        best_match_idx = int(np.argmax(similarities))
        best_similarity = float(similarities[best_match_idx])
        
        # Get data row from dataset
        row = low_score_df.iloc[best_match_idx]
        
        # Extract fields
        matched_question = row["question_text"]
        agent_response = row["agent_response"]
        overall_score = float(row["overall_score"])
        task_id = row["task_id"]
        
        tasks.append({
            "query_idx": query_idx,
            "master_question": query,
            "question": matched_question,
            "agent_response": agent_response,
            "overall_score": overall_score,
            "similarity": best_similarity,
            "task_id": task_id
        })

    results = [None] * len(tasks) # Pre-allocate results to preserve input order
    completed_count = 0

    print(f"Submitting {num_queries} QA pairs for concurrent evaluation...")
    
    # Run evaluations in a ThreadPoolExecutor
    with ThreadPoolExecutor(max_workers=config.MAX_WORKERS) as executor:
        # Submit tasks
        future_to_task = {
            executor.submit(evaluate_response, client, task["question"], task["agent_response"]): task
            for task in tasks
        }
        
        for future in as_completed(future_to_task):
            task = future_to_task[future]
            query_idx = task["query_idx"]
            
            try:
                eval_result = future.result()
            except Exception as exc:
                print(f"Match {query_idx + 1} generated an exception: {exc}")
                eval_result = {
                    "judge_score": 0.0,
                    "reasoning": f"Evaluation error: {exc}"
                }
                
            results[query_idx] = {
                "master_question": task["master_question"],
                "question": task["question"],
                "agent_response": task["agent_response"],
                "overall_score": task["overall_score"],
                "judge_score": eval_result["judge_score"],
                "reasoning": eval_result["reasoning"],
                "similarity": task["similarity"],
                "task_id": task["task_id"]
            }
            
            completed_count += 1
            if completed_count % 5 == 0 or completed_count == num_queries:
                print(f"Progress: Evaluated {completed_count}/{num_queries} items...")

    # Build final DataFrame
    evaluation_df = pd.DataFrame(results)
    
    print(f"Saving evaluation results in {config.EVALUATION_CSV}...")
    evaluation_df.to_csv(config.EVALUATION_CSV, index=False)
    print("Evaluation analysis completed successfully.")
