import os
import json
from concurrent.futures import ThreadPoolExecutor, as_completed
import numpy as np
import pandas as pd
from google import genai
from google.genai import types
from pydantic import BaseModel, Field

import config

class JudgeEvaluation(BaseModel):
    judge_score: float = Field(description="Score between 0.0 and 1.0 representing the correctness, validity, and helpfulness of the agent's response to the user's question.")
    reasoning: str = Field(description="Reasoning explaining the evaluation of the response relative to the user's question, and why this score was assigned.")


def evaluate_response(client: genai.Client, question: str, agent_response: str) -> dict:
    """Uses Gemini to evaluate a question-answer pair and returns a dict with score and reasoning."""
    if client is None:
        # Mock mode: return pseudo-random scores and a mock explanation
        # Add a short delay to simulate real latency for testing concurrency
        import time
        time.sleep(0.1)
        rng = np.random.default_rng(hash(question + agent_response) & 0xffffffff)
        mock_score = round(rng.uniform(0.1, 0.95), 2)
        mock_reasoning = f"Mock evaluation: The response seems reasonably accurate but has some minor issues (Mock score: {mock_score})."
        return {
            "judge_score": mock_score,
            "reasoning": mock_reasoning
        }

    prompt = f"""
    You are an expert AI quality assurance judge evaluating responses generated by a virtual agent assistant.
    
    Evaluate the following user question and virtual agent assistant's response:
    
    User Question:
    "{question}"
    
    Agent's Response:
    "{agent_response}"
    
    Your task:
    1. Check if the agent's response is valid, correct, accurate, and completely answers the user's question.
    2. Assign a judge_score between 0.0 (completely incorrect/incoherent/unhelpful) and 1.0 (completely correct/helpful/accurate).
    3. Provide a clear reasoning explaining your evaluation, highlighting any missing information or discrepancies.
    """

    try:
        response = client.models.generate_content(
            model=config.JUDGE_MODEL,
            contents=prompt,
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                response_schema=JudgeEvaluation,
            ),
        )
        
        parsed_result = response.parsed
        if parsed_result:
            return {
                "judge_score": float(parsed_result.judge_score),
                "reasoning": parsed_result.reasoning
            }
        else:
            # Fallback in case of raw text
            data = json.loads(response.text)
            return {
                "judge_score": float(data.get("judge_score", 0.0)),
                "reasoning": data.get("reasoning", "Parsed result was empty.")
            }
    except Exception as e:
        print(f"Evaluation failed: {e}. Returning default values.")
        return {
            "judge_score": 0.0,
            "reasoning": f"Evaluation error: {e}"
        }


def run_analysis_pipeline(client: genai.Client, similarity_matrix: np.ndarray, input_queries: list[str], low_score_df: pd.DataFrame) -> None:
    """
    For each master_question, find all matched questions from the dataset that exceed SIMILARITY_THRESHOLD.
    If no matches exceed the threshold, falls back to the single best match.
    Extract the question, agent_response, overall_score.
    De-duplicates unique QA pairs to avoid redundant LLM calls.
    Call Gemini concurrently to score unique QA pairs.
    Maps results back to all matched relations and saves to config.EVALUATION_CSV.
    """
    print(f"\n--- Running Response Evaluation Agent (Judge Agent) in Parallel ({config.MAX_WORKERS} workers) ---")
    
    num_queries = len(input_queries)
    if num_queries == 0 or low_score_df.empty:
        print("No queries or dataset records available for analysis.")
        return

    # 1. Collect all matched relationships (queries to dataset rows)
    relations = []
    for query_idx, query in enumerate(input_queries):
        similarities = similarity_matrix[query_idx]
        
        # Find all indices exceeding similarity threshold
        matched_indices = np.where(similarities >= config.SIMILARITY_THRESHOLD)[0]
        
        # If no matches exceed threshold, fallback to the single best match (argmax)
        if len(matched_indices) == 0:
            best_idx = int(np.argmax(similarities))
            matched_indices = [best_idx]
            
        for idx in matched_indices:
            best_similarity = float(similarities[idx])
            row = low_score_df.iloc[idx]
            
            relations.append({
                "master_question": query,
                "question": row["question_text"],
                "agent_response": row["agent_response"],
                "overall_score": float(row["overall_score"]),
                "similarity": best_similarity,
                "task_id": row["task_id"] if pd.notna(row["task_id"]) else ""
            })

    # 2. Extract unique QA pairs to evaluate (by task_id or question+response combo)
    unique_tasks = {}
    for rel in relations:
        key = rel["task_id"] if rel["task_id"] else (rel["question"], rel["agent_response"])
        if key not in unique_tasks:
            unique_tasks[key] = {
                "question": rel["question"],
                "agent_response": rel["agent_response"]
            }

    unique_keys = list(unique_tasks.keys())
    total_unique = len(unique_keys)
    print(f"Found {len(relations)} matching pairs. De-duplicated to {total_unique} unique QA pairs to evaluate.")
    
    eval_results = {}
    completed_count = 0

    # Run evaluations in a ThreadPoolExecutor for unique tasks
    if total_unique > 0:
        print(f"Submitting {total_unique} unique QA pairs for concurrent evaluation...")
        with ThreadPoolExecutor(max_workers=config.MAX_WORKERS) as executor:
            future_to_key = {
                executor.submit(evaluate_response, client, unique_tasks[key]["question"], unique_tasks[key]["agent_response"]): key
                for key in unique_keys
            }
            
            for future in as_completed(future_to_key):
                key = future_to_key[future]
                try:
                    eval_result = future.result()
                except Exception as exc:
                    print(f"Evaluation for key {key} generated an exception: {exc}")
                    eval_result = {
                        "judge_score": 0.0,
                        "reasoning": f"Evaluation error: {exc}"
                    }
                
                eval_results[key] = eval_result
                completed_count += 1
                if completed_count % 5 == 0 or completed_count == total_unique:
                    print(f"Progress: Evaluated {completed_count}/{total_unique} unique items...")

    # 3. Map evaluation results back to all matched relations
    results = []
    for rel in relations:
        key = rel["task_id"] if rel["task_id"] else (rel["question"], rel["agent_response"])
        eval_res = eval_results.get(key, {"judge_score": 0.0, "reasoning": "Missing evaluation"})
        
        overall_score = rel["overall_score"]
        judge_score = eval_res["judge_score"]
        score_diff = round(abs(overall_score - judge_score), 4)
            
        results.append({
            "master_question": rel["master_question"],
            "question": rel["question"],
            "agent_response": rel["agent_response"],
            "overall_score": overall_score,
            "judge_score": judge_score,
            "score_diff": score_diff,
            "reasoning": eval_res["reasoning"],
            "similarity": rel["similarity"],
            "task_id": rel["task_id"]
        })

    # Build final DataFrame
    evaluation_df = pd.DataFrame(results)
    
    # Sort descending by absolute score difference
    evaluation_df = evaluation_df.sort_values(by="score_diff", ascending=False)
    
    print(f"Saving evaluation results in {config.EVALUATION_CSV}...")
    evaluation_df.to_csv(config.EVALUATION_CSV, index=False)
    print("Evaluation analysis completed successfully.")
